ALTER TABLE t_student ADD telephone VARCHAR(255);

DROP TABLE IF EXISTS `t_cost`;
CREATE TABLE `t_cost` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `age` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;